services:
  ml:
    build: ./ml
    container_name: ml
    ports:
      - "9000:8000"

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - ml
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/proj/backend/storage
    environment:
      ML_SERVICE_URL: http://ml:8000/infer
      STORAGE_DIR: /proj/backend/storage
      EXISTENCE_SECONDS: 86400


  frontend:
    build: ./frontend
    container_name: frontend

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf/nginx.docker.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend