mode: train # options: train, finetune
epochs: 150
lr: 1e-3
batch_size: 4
accumulation_steps: 8
optimizer: adamw
scheduler: cosine
weight_decay: 1e-5
bce_weight: 0.5
grad_clip: 1.0
resume: null # path to checkpoint to resume training from
checkpoint_every: 10
seed: 1337

# finetune
finetune_lr: 1e-4
freeze_encoder: true
kfold: 4